[package]
name = "test-benchmark-iai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iai = "0.1"

[[bench]]
name = "my_benchmark"
harness = false
